#! /bin/sh

#######################
# Functions and utils #
#######################
xresource() {
    xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

######################
#     Autostart      #
######################
if [[ "$(xrandr -q | grep -w connected | wc -l)" -eq 2 ]]; then
    xrandr --output HDMI1 --left-of eDP1 --auto \
        && feh --bg-fill $WALLPAPER \
        && bspc monitor HDMI1 -d 1 2 3 4 5 \
        && bspc monitor eDP1 -d 6 7 8 9 10
else
    bspc monitor eDP1 -d 1 2 3 4 5
fi

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr
pgrep -x dunst > /dev/null || dunst -lf "$(xresource foreground)" -nf "$(xresource foreground)" -cf "$(xresource foreground)" \
    -lb "$(xresource background)" -nb "$(xresource background)" -cb "$(xresource background)" \
    -lfr "$(xresource color3)" -nfr "$(xresource color6)" -cfr "$(xresource color1)" &
wmname LG3D

#######################
#        Colors       #
#######################
#COLORS="$HOME"/.cache/wal/colors.sh
#[[ -s "$COLORS" ]] && source $COLORS

bspc config focused_border_color "$(xresource color8)"
bspc config normal_border_color  "$(xresource background)"


########################
#    General tweaks    #
########################
bspc config border_width          1 
bspc config window_gap            12
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config single_monocle        true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true


########################
#         Rules        #
########################
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a gimp state=floating
bspc rule -a steam state=floating
bspc rule -a emacs state=tiling
